variable "app_name" {}
variable "env" {}
variable "default_ami" {}
variable "availability_zones" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "db_name" {}
variable "db_instance_class" {}
variable "db_instance_id" {}
variable "db_allocated_storage" {}
variable "db_username" {}
variable "db_password" {}
variable "cache_node_type" {}
